apiVersion: v1
kind: Service
metadata:
  name: olappservcie
  namespace: generic1prod
spec:
  type: NodePort
  selector:
    app: olapp
  ports:
    - protocol: TCP
      port: 9082
      targetPort: 9082
      nodePort: 32003
